<?php
/**
 * WordPress Configuration with Dynamic URL Support
 * Generated by DevLauncher by Datadox
 * 
 * This configuration allows WordPress to work with multiple URLs:
 * - localhost:{{WP_PORT}} (for local development)
 * - host.docker.internal:{{WP_PORT}} (for Docker MCP access)
 * - {{PROJECT_NAME}}_wordpress (for container-to-container communication)
 */

// ** Dynamic URL Configuration ** //
if (!empty($_SERVER['HTTP_HOST'])) {
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
    $dynamic_url = $protocol . $_SERVER['HTTP_HOST'];
    
    define('WP_HOME', $dynamic_url);
    define('WP_SITEURL', $dynamic_url);
} else {
    // Fallback for WP-CLI and other non-HTTP contexts
    define('WP_HOME', 'http://localhost:{{WP_PORT}}');
    define('WP_SITEURL', 'http://localhost:{{WP_PORT}}');
}

// ** Database settings ** //
define('DB_NAME', '{{PROJECT_NAME}}_db');
define('DB_USER', '{{PROJECT_NAME}}_user');
define('DB_PASSWORD', 'secure_password_123');
define('DB_HOST', 'mysql:3306');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

// ** Authentication Unique Keys and Salts ** //
// These will be generated during installation
define('AUTH_KEY',         'put your unique phrase here');
define('SECURE_AUTH_KEY',  'put your unique phrase here');
define('LOGGED_IN_KEY',    'put your unique phrase here');
define('NONCE_KEY',        'put your unique phrase here');
define('AUTH_SALT',        'put your unique phrase here');
define('SECURE_AUTH_SALT', 'put your unique phrase here');
define('LOGGED_IN_SALT',   'put your unique phrase here');
define('NONCE_SALT',       'put your unique phrase here');

// ** WordPress Database Table prefix ** //
$table_prefix = 'wp_';

// ** For developers: WordPress debugging mode ** //
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
define('WP_ENVIRONMENT_TYPE', 'local');
define('AUTOMATIC_UPDATER_DISABLED', true);

// ** Memory and upload limits ** //
@ini_set('memory_limit', '256M');
@ini_set('upload_max_filesize', '64M');
@ini_set('post_max_size', '64M');

// ** SMTP Settings for Mailpit ** //
define('SMTP_HOST', 'mailpit');
define('SMTP_PORT', 1025);
define('SMTP_SECURE', '');

// ** Allow WordPress to detect HTTPS when behind a reverse proxy ** //
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
    $_SERVER['HTTPS'] = 'on';
}

// ** Disable canonical redirects for local development ** //
remove_filter('template_redirect', 'redirect_canonical');

// ** Allow all hosts (for Docker environments) ** //
if (!defined('WP_CLI')) {
    define('WP_ACCESSIBLE_HOSTS', '*');
}

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';